### ISSUE TITLE
TypeError: __new__() got an unexpected keyword argument 'serialized_options'

### ISSUE THREAD

**Issue by Gstalker** [cq674350529/deflat#1]
ubuntu ver18，py3.6，angr8，运行deflat.py和bogus.py时报错
TypeError: __new__() got an unexpected keyword argument 'serialized_options'

**Comment by Gstalker** [comment]
ok，问题已经找到，angr版本号不同导致的。但是在安装了正确的angr之后仍然有报错:
Traceback (most recent call last):
  File "deflat.py", line 96, in <module>
    supergraph = am_graph.to_supergraph(target_function.transition_graph)
AttributeError: 'NoneType' object has no attribute 'transition_graph'

**Comment by cq674350529** [comment]
Hi, I ran the `deflat.py` with the lastet `angr` (version 8.19.7.25) and `python3.5` successfully. I guess it has nothing to do with the version of `angr` and `python`.
