### ISSUE TITLE
not able to get function in new version of angr.

### ISSUE THREAD

**Issue by aynakeya** [cq674350529/deflat#12]
I'm currently using angr version 9.2.106 in my environment. I'm encountering an issue where the `target_function` is returning `None` when excuting the following code:

```python
target_function = cfg.functions.get(start)
```

I found that this issue can be resolved by replacing the above code with:

```python
target_function = cfg.kb.functions.get_by_addr(project.loader.main_object.mapped_base + start)
```

**Comment by cq674350529** [comment]
Hi @aynakeya, thanks for your feedback. I did't try with the latest angr version. According to your description, it seemed that the binary you tested has PIE enabled. Of course, the angr api may has also changed.

I will update the code to take this into account. Thanks again.

**Comment by aynakeya** [comment]
thank you for your feedback. You were right; my binary does have PIE enabled. I didn’t realize it was a PIE-related problem at the time :(

![image](https://github.com/cq674350529/deflat/assets/32156054/1560ba6c-8244-4310-8664-5f538b53c40d)

Additionally, I forgot to mention another modification needed to make the program work with PIE. Without this modification, the prologue address will not match.

```python
    if prologue_node is None or prologue_node.addr != (start + base_addr):
        print("Something must be wrong...")
        sys.exit(-1)
```
