### ISSUE TITLE
patch 错误 patch error

### ISSUE THREAD

**Issue by xiran210** [cq674350529/deflat#13]
在 `util.py` 中 `ins_b_jmp_hex_arm64` 函数中  In the ins-b_jmp_hex_arm64 function in utilit.py

此语句错误 This statement is incorrect
```
patch_ins_hex = struct.pack('<I', ((0x14000000 | 0x03ffffff) - (cur_addr - target_addr) // 4))
```
应为 Should be
```
patch_ins_hex = struct.pack('<I', ((0x14000000 | 0x03ffffff) - (cur_addr - target_addr - 4) // 4))
```

**Comment by cq674350529** [comment]
Thanks for your feedback, fixed via https://github.com/cq674350529/deflat/commit/2b57c9f38d2a2f34ac2065cd0cd35637a63f5b18. If any problems, feel free to reopen this issue.
