### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'transition_graph'

### ISSUE THREAD

**Issue by Gstalker** [cq674350529/deflat#2]
安装一致版本的angr之后，py3.6.0，grapy.py已复制到相同目录下，运行deflat.py时报错：
Traceback (most recent call last):
File "deflat.py", line 96, in 
supergraph = am_graph.to_supergraph(target_function.transition_graph)
AttributeError: 'NoneType' object has no attribute 'transition_graph'

**Comment by cq674350529** [comment]
@CSU-Dreamstalker According to the error message, it seems to fail to get the target function. Please make sure if you passed the right function address as the command line arg. 
By the way, did you run the `deflat.py` with the provided example or your own binary?

**Comment by Gstalker** [comment]
Using the provided example.
command:python3 deflat.py check_passwd 0x400530

**Comment by Gstalker** [comment]
THX,I've found the problem.That my mistake.(poor eng,sorry
