### ISSUE TITLE
不支持arm吗

### ISSUE THREAD

**Issue by SuperYogurt** [cq674350529/deflat#3]

**Comment by cq674350529** [comment]
Hi,
The method is suitable for other archs, such as `ARM`, `MIPS`. But currently, it only supports x86 arch becaure it depends on specific opcodes when patching the original binary.

https://github.com/cq674350529/deflat/blob/b7ff324eaf000045e6c5bbd2b8b3134c38e185fd/flat_control_flow/deflat.py#L83-L88

I will have a try and adapt it to more archs(like `ARM`, `MIPS`) as soon as possbile, maybe tonight.

Also, pull requests are welcomed.

Thanks.

**Comment by cq674350529** [comment]
@SuperYogurt  Currently it supports `arm` arch (`armv7 32bit`) via https://github.com/cq674350529/deflat/pull/4. You can get the latest code and have a try.

Actually, I only tested it on `ARM(LSB)`, but it should work on `ARM(MSB)` too. 

If any issues, feedback is welcomed.

Thanks!

**Comment by SuperYogurt** [comment]
> @SuperYogurt Currently it supports `arm` arch (`armv7 32bit`) via #4. You can get the latest code and have a try.
> 
> Actually, I only tested it on `ARM(LSB)`, but it should work on `ARM(MSB)` too.
> 
> If any issues, feedback is welcomed.
> 
> Thanks!

alright, thank you very much
