### ISSUE TITLE
Will it support arm64?

### ISSUE THREAD

**Issue by LittleLydia** [cq674350529/deflat#6]
It seems that one angr dependency cle doesn't support mach-o backend very well. What would be the possible ways to solve it?

**Comment by cq674350529** [comment]
Do you have some binaries for testing purpose? Both raw binary and flatted binary with symbols compiled would be better.

If not, I can only have a try with `aarch64` in Linux env.

**Comment by LittleLydia** [comment]
Thanks for the reply. I can provide some flattened arm64 binary with its raw binary later.

**Comment by LittleLydia** [comment]
[testsformacho.zip](https://github.com/cq674350529/deflat/files/4558426/testsformacho.zip)

Here it is!

**Comment by cq674350529** [comment]
Thanks! I'll have a try.

**Comment by cq674350529** [comment]
@LittleLydia Currently, the aarch64 is supported via https://github.com/cq674350529/deflat/pull/7.

By the way, I didn't come accross any issues related to `cle` at the moment. In addition, another issue was fixed when more than one function call exist in the same block.

You can have a try. If any issues, feedback is welcomed.

Thanks!

**Comment by LittleLydia** [comment]
Cle does not support loading two and more binaries at the same time. So if a macho depends on many libraries, it will fail. Have emailed you a practical example and the log file. You can take a look.

**Comment by cq674350529** [comment]
I tried the binary you provided with the latest `angr`, and I didn't came across the issue you mentioned.

However, `angr` seems to output *wrong* blocks of the target function. In addition, the flatted structure of the target function is different from those in demo binary.  It'll take some time to debug it, since the binary is soooooooo big.

By the way, are you sure the target function is flatted?

Thanks!

**Comment by cq674350529** [comment]
@LittleLydia Oops, it's hard for me to debug this binary currently. Since it's soooooooooo big, it will consume all my computer resources(`CPU`, `memory`) every time I run it with `angr`. Also, the IDA is also sloooooooooow to respond.
