### ISSUE TITLE
This Script support arm64 ios dylib binary?? 

### ISSUE THREAD

**Issue by simhigo** [cq674350529/deflat#8]
This Script support arm64 ios dylib binary?? 

ios dylib binary load failed... 

raise CLECompatibilityError("Unable to find a loader backend for %s.  Perhaps try the 'blob' loader?" % spec)

**Comment by cq674350529** [comment]
All the basic stuffs such as parsing and loading the binary are dependent on the capability of `angr`.

Actually, I only tested a demo MachO binary `check_passwd_arm64_flat`. According to the log above, it seems that the `angr` failed to load the binary.

Can you provide the binary used? Maybe I can have a try.

Thanks!

**Comment by simhigo** [comment]
I'm sorry, but I can't seem to provide that binary.

Thank you for answer.

**Comment by cq674350529** [comment]
It's ok. Another suggestion: try the suggested 'blob' loader.

By the way, a demo binary is also OK if it can cause the same issue.
